package com.android.tonight8.dao.entity;

import com.android.tonight8.dao.DaoSession;

import de.greenrobot.dao.DaoException;

import com.android.tonight8.dao.UserDao;
import com.android.tonight8.dao.VoteItemOptionDao;
import com.android.tonight8.dao.VoteResultDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table VOTE_RESULT.
 */
public class VoteResult {

    private long id;
    private Long userId;
    private Long voteItemOptionId;

    /**
     * Used to resolve relations
     */
    private transient DaoSession daoSession;

    /**
     * Used for active entity operations.
     */
    private transient VoteResultDao myDao;

    private User user;
    private Long user__resolvedKey;

    private VoteItemOption voteItemOption;
    private Long voteItemOption__resolvedKey;


    public VoteResult() {
    }

    public VoteResult(long id) {
        this.id = id;
    }

    public VoteResult(long id, Long userId, Long voteItemOptionId) {
        this.id = id;
        this.userId = userId;
        this.voteItemOptionId = voteItemOptionId;
    }

    /**
     * called by internal mechanisms, do not call yourself.
     */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getVoteResultDao() : null;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getVoteItemOptionId() {
        return voteItemOptionId;
    }

    public void setVoteItemOptionId(Long voteItemOptionId) {
        this.voteItemOptionId = voteItemOptionId;
    }

    /**
     * To-one relationship, resolved on first access.
     */
    public User getUser() {
        Long __key = this.userId;
        if (user__resolvedKey == null || !user__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            UserDao targetDao = daoSession.getUserDao();
            User userNew = targetDao.load(__key);
            synchronized (this) {
                user = userNew;
                user__resolvedKey = __key;
            }
        }
        return user;
    }

    public void setUser(User user) {
        synchronized (this) {
            this.user = user;
            userId = user == null ? null : user.getId();
            user__resolvedKey = userId;
        }
    }

    /**
     * To-one relationship, resolved on first access.
     */
    public VoteItemOption getVoteItemOption() {
        Long __key = this.voteItemOptionId;
        if (voteItemOption__resolvedKey == null || !voteItemOption__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            VoteItemOptionDao targetDao = daoSession.getVoteItemOptionDao();
            VoteItemOption voteItemOptionNew = targetDao.load(__key);
            synchronized (this) {
                voteItemOption = voteItemOptionNew;
                voteItemOption__resolvedKey = __key;
            }
        }
        return voteItemOption;
    }

    public void setVoteItemOption(VoteItemOption voteItemOption) {
        synchronized (this) {
            this.voteItemOption = voteItemOption;
            voteItemOptionId = voteItemOption == null ? null : voteItemOption.getId();
            voteItemOption__resolvedKey = voteItemOptionId;
        }
    }

    /**
     * Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context.
     */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.delete(this);
    }

    /**
     * Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context.
     */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.update(this);
    }

    /**
     * Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context.
     */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.refresh(this);
    }

}
